### ISSUE TITLE
[FIXED] Error while trying to install mysqldb

### ISSUE THREAD

**Issue by primalbet** [alexferl/flask-mysqldb#13]
I ran a command `pip install flask-mysqldb` and I get this

```
Collecting flask-mysqldb
  Using cached Flask-MySQLdb-0.2.0.tar.gz
Requirement already satisfied: Flask>=0.10 in ./venv/lib/python3.6/site-packages (from flask-mysqldb)
Collecting mysqlclient (from flask-mysqldb)
  Using cached mysqlclient-1.3.12.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wrldt09x/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-wrldt09x/mysqlclient/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-build-wrldt09x/mysqlclient/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wrldt09x/mysqlclient/
```

I was missing mysql_config for some reason, needed to install `sudo apt-get install libmysqlclient-dev` first, and then it worked.

**Comment by rauf-sudo** [comment]
How to install libmysqlclient-dev is possible?

**Comment by oumar90** [comment]
> I was missing mysql_config for some reason, needed to install sudo apt-get install libmysqlclient-dev first, and then it worked.

> 
Thanks, it work for me!

**Comment by selvanthamarai** [comment]
> I ran a command `pip install flask-mysqldb` and I get this
> 
> ```
> Collecting flask-mysqldb
>   Using cached Flask-MySQLdb-0.2.0.tar.gz
> Requirement already satisfied: Flask>=0.10 in ./venv/lib/python3.6/site-packages (from flask-mysqldb)
> Collecting mysqlclient (from flask-mysqldb)
>   Using cached mysqlclient-1.3.12.tar.gz
>     Complete output from command python setup.py egg_info:
>     /bin/sh: 1: mysql_config: not found
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-wrldt09x/mysqlclient/setup.py", line 17, in <module>
>         metadata, options = get_config()
>       File "/tmp/pip-build-wrldt09x/mysqlclient/setup_posix.py", line 44, in get_config
>         libs = mysql_config("libs_r")
>       File "/tmp/pip-build-wrldt09x/mysqlclient/setup_posix.py", line 26, in mysql_config
>         raise EnvironmentError("%s not found" % (mysql_config.path,))
>     OSError: mysql_config not found
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wrldt09x/mysqlclient/
> ```
> 
> I was missing mysql_config for some reason, needed to install `sudo apt-get install libmysqlclient-dev` first, and then it worked.

Its really work fo me thanks a lot

**Comment by Danylo450** [comment]
He ejecutado el comando pip install flask-mysqldb y obtengo esto:
Collecting Flask-MySQLdb
  Using cached https://files.pythonhosted.org/packages/62/e3/955c845efe1aacf30c8e2607470544ede36aa1044f6382c809f13e014104/Flask-MySQLdb-0.2.0.tar.gz
Requirement already satisfied: Flask>=0.10 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask-MySQLdb) (1.1.1)
Collecting mysqlclient
  Using cached https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz
Requirement already satisfied: Werkzeug>=0.15 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask>=0.10->Flask-MySQLdb) (0.16.0)
Requirement already satisfied: Jinja2>=2.10.1 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask>=0.10->Flask-MySQLdb) (2.10.3)
Requirement already satisfied: click>=5.1 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask>=0.10->Flask-MySQLdb) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask>=0.10->Flask-MySQLdb) (1.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Jinja2>=2.10.1->Flask>=0.10->Flask-MySQLdb) (1.1.1)
Installing collected packages: mysqlclient, Flask-MySQLdb
    Running setup.py install for mysqlclient ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\garna\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\garna\\AppData\\Local\\Temp\\pip-install-ysot700u\\mysqlclient\\setup.py'"'"'; __file__='"'"'C:\\Users\\garna\\AppData\\Local\\Temp\\pip-install-ysot700u\\mysqlclient\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\garna\AppData\Local\Temp\pip-record-nirxfo_s\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\garna\AppData\Local\Temp\pip-install-ysot700u\mysqlclient\
    Complete output (24 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\MySQLdb
    copying MySQLdb\__init__.py -> build\lib.win32-3.8\MySQLdb
    copying MySQLdb\_exceptions.py -> build\lib.win32-3.8\MySQLdb
    copying MySQLdb\compat.py -> build\lib.win32-3.8\MySQLdb
    copying MySQLdb\connections.py -> build\lib.win32-3.8\MySQLdb
    copying MySQLdb\converters.py -> build\lib.win32-3.8\MySQLdb
    copying MySQLdb\cursors.py -> build\lib.win32-3.8\MySQLdb
    copying MySQLdb\release.py -> build\lib.win32-3.8\MySQLdb
    copying MySQLdb\times.py -> build\lib.win32-3.8\MySQLdb
    creating build\lib.win32-3.8\MySQLdb\constants
    copying MySQLdb\constants\__init__.py -> build\lib.win32-3.8\MySQLdb\constants
    copying MySQLdb\constants\CLIENT.py -> build\lib.win32-3.8\MySQLdb\constants
    copying MySQLdb\constants\CR.py -> build\lib.win32-3.8\MySQLdb\constants
    copying MySQLdb\constants\ER.py -> build\lib.win32-3.8\MySQLdb\constants
    copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win32-3.8\MySQLdb\constants
    copying MySQLdb\constants\FLAG.py -> build\lib.win32-3.8\MySQLdb\constants
    running build_ext
    building 'MySQLdb._mysql' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\garna\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\garna\\AppData\\Local\\Temp\\pip-install-ysot700u\\mysqlclient\\setup.py'"'"'; __file__='"'"'C:\\Users\\garna\\AppData\\Local\\Temp\\pip-install-ysot700u\\mysqlclient\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\garna\AppData\Local\Temp\pip-record-nirxfo_s\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by aakankshamudgal** [comment]
> 
> 
> He ejecutado el comando pip install flask-mysqldb y obtengo esto:
> Collecting Flask-MySQLdb
> Using cached https://files.pythonhosted.org/packages/62/e3/955c845efe1aacf30c8e2607470544ede36aa1044f6382c809f13e014104/Flask-MySQLdb-0.2.0.tar.gz
> Requirement already satisfied: Flask>=0.10 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask-MySQLdb) (1.1.1)
> Collecting mysqlclient
> Using cached https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz
> Requirement already satisfied: Werkzeug>=0.15 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask>=0.10->Flask-MySQLdb) (0.16.0)
> Requirement already satisfied: Jinja2>=2.10.1 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask>=0.10->Flask-MySQLdb) (2.10.3)
> Requirement already satisfied: click>=5.1 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask>=0.10->Flask-MySQLdb) (7.0)
> Requirement already satisfied: itsdangerous>=0.24 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Flask>=0.10->Flask-MySQLdb) (1.1.0)
> Requirement already satisfied: MarkupSafe>=0.23 in c:\users\garna\appdata\local\programs\python\python38-32\lib\site-packages (from Jinja2>=2.10.1->Flask>=0.10->Flask-MySQLdb) (1.1.1)
> Installing collected packages: mysqlclient, Flask-MySQLdb
> Running setup.py install for mysqlclient ... error
> ERROR: Command errored out with exit status 1:
> command: 'c:\users\garna\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\garna\AppData\Local\Temp\pip-install-ysot700u\mysqlclient\setup.py'"'"'; **file**='"'"'C:\Users\garna\AppData\Local\Temp\pip-install-ysot700u\mysqlclient\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\garna\AppData\Local\Temp\pip-record-nirxfo_s\install-record.txt' --single-version-externally-managed --compile
> cwd: C:\Users\garna\AppData\Local\Temp\pip-install-ysot700u\mysqlclient
> Complete output (24 lines):
> running install
> running build
> running build_py
> creating build
> creating build\lib.win32-3.8
> creating build\lib.win32-3.8\MySQLdb
> copying MySQLdb__init__.py -> build\lib.win32-3.8\MySQLdb
> copying MySQLdb_exceptions.py -> build\lib.win32-3.8\MySQLdb
> copying MySQLdb\compat.py -> build\lib.win32-3.8\MySQLdb
> copying MySQLdb\connections.py -> build\lib.win32-3.8\MySQLdb
> copying MySQLdb\converters.py -> build\lib.win32-3.8\MySQLdb
> copying MySQLdb\cursors.py -> build\lib.win32-3.8\MySQLdb
> copying MySQLdb\release.py -> build\lib.win32-3.8\MySQLdb
> copying MySQLdb\times.py -> build\lib.win32-3.8\MySQLdb
> creating build\lib.win32-3.8\MySQLdb\constants
> copying MySQLdb\constants__init__.py -> build\lib.win32-3.8\MySQLdb\constants
> copying MySQLdb\constants\CLIENT.py -> build\lib.win32-3.8\MySQLdb\constants
> copying MySQLdb\constants\CR.py -> build\lib.win32-3.8\MySQLdb\constants
> copying MySQLdb\constants\ER.py -> build\lib.win32-3.8\MySQLdb\constants
> copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win32-3.8\MySQLdb\constants
> copying MySQLdb\constants\FLAG.py -> build\lib.win32-3.8\MySQLdb\constants
> running build_ext
> building 'MySQLdb._mysql' extension
> error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
> ----------------------------------------
> ERROR: Command errored out with exit status 1: 'c:\users\garna\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\garna\AppData\Local\Temp\pip-install-ysot700u\mysqlclient\setup.py'"'"'; **file**='"'"'C:\Users\garna\AppData\Local\Temp\pip-install-ysot700u\mysqlclient\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\garna\AppData\Local\Temp\pip-record-nirxfo_s\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

I'm also getting the same error! Could you please help me to fix this

**Comment by nishit0709** [comment]
> > I ran a command `pip install flask-mysqldb` and I get this
> > ```
> > Collecting flask-mysqldb
> >   Using cached Flask-MySQLdb-0.2.0.tar.gz
> > Requirement already satisfied: Flask>=0.10 in ./venv/lib/python3.6/site-packages (from flask-mysqldb)
> > Collecting mysqlclient (from flask-mysqldb)
> >   Using cached mysqlclient-1.3.12.tar.gz
> >     Complete output from command python setup.py egg_info:
> >     /bin/sh: 1: mysql_config: not found
> >     Traceback (most recent call last):
> >       File "<string>", line 1, in <module>
> >       File "/tmp/pip-build-wrldt09x/mysqlclient/setup.py", line 17, in <module>
> >         metadata, options = get_config()
> >       File "/tmp/pip-build-wrldt09x/mysqlclient/setup_posix.py", line 44, in get_config
> >         libs = mysql_config("libs_r")
> >       File "/tmp/pip-build-wrldt09x/mysqlclient/setup_posix.py", line 26, in mysql_config
> >         raise EnvironmentError("%s not found" % (mysql_config.path,))
> >     OSError: mysql_config not found
> >     
> >     ----------------------------------------
> > Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wrldt09x/mysqlclient/
> > ```
> > 
> > 
> > I was missing mysql_config for some reason, needed to install `sudo apt-get install libmysqlclient-dev` first, and then it worked.
> 
> Its really work fo me thanks a lot

>It worked for me too, thanks a lot

**Comment by cyborg2006** [comment]
How can fix the same in mac OSX? Please let me know as well.

**Comment by kwamena98** [comment]
I think this can help you out If maybe you need to install mysqldb on your linux I think this can really help you out:

**sudo apt-get install mysql-server
sudo apt-get install libmysqlclient-dev
pip3 install flask-mysqldb**
