### ISSUE TITLE
unable to install flask-mysqldb in google app engine

### ISSUE THREAD

**Issue by ingenium21** [alexferl/flask-mysqldb#17]
Hey Guys, 

I'm trying to install flask-mysqldb in my app engine environment and I get the following error.

> Collecting flask-mysqldb Using cached https://files.pythonhosted.org/packages/62/e3/955c845efe1aacf30c8e2607470544ede36aa1044f6382c809f13e014104/Flask-MySQLdb-0.2.0.tar.gz 
> Collecting Flask>=0.10 (from flask-mysqldb) Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl Collecting mysqlclient (from flask-mysqldb) 
> Using cached https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz 
> Complete output from command python setup.py egg_info: sh: 1: mysql_config: not found 
> Traceback (most recent call last): File "", line 1, in 
> File "/tmp/pip-install-i07vlu/mysqlclient/setup.py", line 18, in metadata, options = get_config() 
> File "setup_posix.py", line 53, in get_config libs = mysql_config("libs_r") 
> File "setup_posix.py", line 28, in mysql_config raise EnvironmentError("%s not found" % (mysql_config.path,)) 
> EnvironmentError: mysql_config not found
> 
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-i07vlu/mysqlclient/
> 

any help would be very appreciated. 

Thanks!

**Comment by alexferl** [comment]
It's because the environment App Engine is running on is missing some MySQL libraries so flask-mysqldb cannot be installed. Did you check the how-to for using Cloud SQL on App Engine [here](https://cloud.google.com/appengine/docs/standard/python/cloud-sql/using-cloud-sql-mysql)?

It seems you need this in your `app.yaml`:
```
libraries:
- name: MySQLdb
  version: "latest"
```
