### ISSUE TITLE
'NoneType' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by Dmitry-SigmaSW** [alexferl/flask-mysqldb#19]
Hello. I'm using Python3 and have the following code. I'm getting 'NoneType' object has no attribute 'cursor' when I'm trying to use mysql.connection.cursor(). What's wrong with that? Please take to consideration, that I'm using according to the official manual page which is https://flask-mysqldb.readthedocs.io/en/latest/

from flask_mysqldb import MySQL
from flask import Flask, request
app = Flask(__name__)

app.config['MYSQL_HOST'] = 'someip'
app.config['MYSQL_USER'] = 'someuser'
app.config['MYSQL_PASSWORD'] = 'password'
app.config['MYSQL_DB'] = 'rooms'

mysql = MySQL(app)
cur = mysql.connection.cursor()

**Comment by gdadlaney** [comment]
Try creating the cursor inside a flask function, like -

```
@app.route('/')
def hello():
    cur = mysql.connection.cursor()
```

**Comment by alexferl** [comment]
Like @gdadlaney said, the connection needs to be created in a Flask route.

**Comment by codezart** [comment]
There are many instances where it must be in a function that isn't a Flask route.

Like for example in a Flask route that fetching multiple types of data, each separated in functions

**Comment by ChuckPhilips** [comment]
This worked for me:

```    
@app.route('/')
def Index():
    cur = mysql.connect.cursor()
```

**Comment by mahboobulhassan** [comment]
> This worked for me:
> 
> ```
> @app.route('/')
> def Index():
>     cur = mysql.connect.cursor()
> ```

thanks
