### ISSUE TITLE
Error while installing using Pip

### ISSUE THREAD

**Issue by premudeshi** [alexferl/flask-mysqldb#22]
I get an issue while trying to install it using pip. I use the following:
`pip3 install flask-mysqldb`
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

**Comment by InfinityCode777** [comment]
**The same here, I am using Pipenv and I got the error**

`(flask-app) (base) Woos-f8book-pro:flask-app Woos $ pipenv install flask-mysqldb
Installing flask-mysqldb…
Adding flask-mysqldb to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock (02fd75) out of date, updating to (5bf423)…
Locking [dev-packages] dependencies…
✔ Success!
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (02fd75)!
Installing dependencies from Pipfile.lock (02fd75)…
An error occurred while installing mysqlclient==1.4.6 --hash=sha256:4c82187dd6ab3607150fbb1fa5ef4643118f3da122b8ba31c3149ddd9cf0cb39 --hash=sha256:9e6080a7aee4cc6a06b58b59239f20f1d259c1d2fddf68ddeed242d2311c7087 --hash=sha256:f3fdaa9a38752a3b214a6fe79d7cae3653731a53e577821f9187e67cbecb2e16 --hash=sha256:f646f8d17d02be0872291f258cce3813497bc7888cd4712a577fd1e719b2f213! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 14/14 — 00:00:03
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting mysqlclient==1.4.6', '  Using cached mysqlclient-1.4.6.tar.gz (85 kB)']
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '     command: /Users/Woos/.local/share/virtualenvs/flask-app-IPjYP4-i/bin/python3 -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-igm2v7d4/mysqlclient/setup.py\'"\'"\'; __file__=\'"\'"\'/private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-igm2v7d4/mysqlclient/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base /private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-igm2v7d4/mysqlclient/pip-egg-info', '         cwd: /private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-igm2v7d4/mysqlclient/', '    Complete output (12 lines):', '    /bin/sh: mysql_config: command not found', '    /bin/sh: mariadb_config: command not found', '    /bin/sh: mysql_config: command not found', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-igm2v7d4/mysqlclient/setup.py", line 16, in <module>', '        metadata, options = get_config()', '      File "/private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-igm2v7d4/mysqlclient/setup_posix.py", line 61, in get_config', '        libs = mysql_config("libs")', '      File "/private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-igm2v7d4/mysqlclient/setup_posix.py", line 29, in mysql_config', '        raise EnvironmentError("%s not found" % (_mysql_config_path,))', '    OSError: mysql_config not found', '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.']`

**When I ran it in outside the virtual env, I got this**
`(base) Woos-f8book-pro:flask-app Woos$ pip install flask-mysqldb
Collecting flask-mysqldb
  Downloading https://files.pythonhosted.org/packages/62/e3/955c845efe1aacf30c8e2607470544ede36aa1044f6382c809f13e014104/Flask-MySQLdb-0.2.0.tar.gz
Requirement already satisfied: Flask>=0.10 in /anaconda3/lib/python3.7/site-packages (from flask-mysqldb) (1.0.2)
Collecting mysqlclient (from flask-mysqldb)
  Using cached https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-kzbw3s_q/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-kzbw3s_q/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-kzbw3s_q/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h7/yzvlp_9j6bqbs815ntdby5tc0000gn/T/pip-install-kzbw3s_q/mysqlclient/`

**Comment by FernandoTorres** [comment]
same here:

```

**Comment by f3270** [comment]
same here:
```
(env) ubuntu@ip-10:~/dev-app$ pip install flask-mysqldb
Collecting flask-mysqldb
  Downloading Flask-MySQLdb-0.2.0.tar.gz (2.1 kB)
Requirement already satisfied: Flask>=0.10 in ./env/lib/python3.6/site-packages (from flask-mysqldb) (1.1.2)
Collecting mysqlclient
  Downloading mysqlclient-1.4.6.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 2.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/dev-app/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hourhu34/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hourhu34/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wxc2yk2o
         cwd: /tmp/pip-install-hourhu34/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hourhu34/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-hourhu34/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-hourhu34/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Python 3.6.9 on Ubuntu 18.04LTS

**Comment by Brakebusk** [comment]
The problem is with installation of the mysqlclient dependency, which requires cetrain packages:
Debian/Ubuntu: `sudo apt install python3-dev default-libmysqlclient-dev build-essential` 
RHEL/CentOS: `sudo yum install python3-devel mysql-devel`
See: https://pypi.org/project/mysqlclient/

**Comment by georgeoffley** [comment]
> The problem is with installation of the mysqlclient dependency, which requires cetrain packages:
> Debian/Ubuntu: `sudo apt install python3-dev default-libmysqlclient-dev build-essential`
> RHEL/CentOS: `sudo yum install python3-devel mysql-devel`
> See: https://pypi.org/project/mysqlclient/

This worked for me after wrestling with it on a Debian-based docker image.

**Comment by alexferl** [comment]
Thanks @Brakebusk
