### ISSUE TITLE
Add the MYSQL_SSL_CA option

### ISSUE THREAD

**Issue by JafetMo5601** [alexferl/flask-mysqldb#27]
Add the configuration option for `ssl_ca` connection parameters.

**Comment by raoumairwaheed** [comment]
hey, did you find something?

**Comment by JafetMo5601** [comment]
> hey, did you find something?

Hey! 
I had to change the connector, this one could work :)
https://pypi.org/project/flask-mysql-connector/

**Comment by alexferl** [comment]
@JafetMo5601 hadn't seen this, do you mind resending the PR it so I can merge it? Or was it a request?

**Comment by alexferl** [comment]
Possible now with `MYSQL_CUSTOM_OPTIONS`, see README.md.

**Comment by JafetMo5601** [comment]
> Possible now with `MYSQL_CUSTOM_OPTIONS`, see README.md.

Was a request but seems that now should work, will try it as soon as I can. 
Thanks! :)
