### ISSUE TITLE
importError

### ISSUE THREAD

**Issue by waakanni** [alexferl/flask-mysqldb#32]
https://github.com/alexferl/flask-mysqldb/blob/dc1db1e1b64d6d927297d58a00b91b7089b3e1f5/flask_mysqldb/__init__.py#L3C13-L3C13

I get the following error when i imported this module

""""
 from flask_mysqldb import MySQL
File "HOME/venv/lib/python3.11/site-packages/flask_mysqldb/__init__.py", line 3, in <module>
 from flask import _app_ctx_stack, current_app
ImportError: cannot import name '_app_ctx_stack' from 'flask' (HOME/venv/lib/python3.11/site-packages/flask/__init__.py)
""""

**Comment by alexferl** [comment]
Fixed in release v2.0.0.
