### ISSUE TITLE
No module named flaskext.mysql 

### ISSUE THREAD

**Issue by CBaptiste** [alexferl/flask-mysqldb#4]
Hello,

I don't understand what I am doing wrong...
I `pip install` and then tried `from flaskext.mysql import MySQL`or `from flask_mysqldb import MySQL` but I can't get it working : `No module named flask_mysqldb`. Am I the only one ?

Any clue ?

Thx !

**Comment by sergani** [comment]
Hello,

Try this:
`pip install Flask-MySQLdb`

**Comment by alexferl** [comment]
`from flask_mysqldb import MySQL` should definitely work. As @sergani said, make sure the lib is correctly installed.

**Comment by CBaptiste** [comment]
yes, I had done a little mistake, my bad guys !

**Comment by sagarkites** [comment]
still not working

**Comment by OfficialAnchal** [comment]
Its not working

**Comment by guptavirat** [comment]
still not working

**Comment by itoxir** [comment]
still not working

**Comment by AzharUddinSheikh** [comment]
it wont work from 
flaskext.mysql import MySQL  
downlaod old version python and try this 
pip install flaskext

**Comment by bio-informatician** [comment]
This package is not compatible with python3, you may need pymysql or mysql.connector or other alternatives instead of flaskext.
