### ISSUE TITLE
Failed to establish database connection, I wanted to retrieve the db_config

### ISSUE THREAD

**Issue by ravindrakush11** [alexferl/flask-mysqldb#45]
import requests
from sql_database_module import SQLDatabase  # Importing necessary modules

class DatabaseConnection:
    """
    A class to represent a database connection.

    Attributes:
        db: The database connection object.
    """
    def __init__(self, username, password, hostname, port, database):
        """
        Initializes a DatabaseConnection object.

        Parameters:
            username (str): The username for the database connection.
            password (str): The password for the database connection.
            hostname (str): The hostname of the database server.
            port (int): The port number for the database connection.
            database (str): The name of the database.

        Returns:
            None
        """
        try:
            self.db = SQLDatabase.from_uri(f"postgresql://{username}:{password}@{hostname}:{port}/{database}")
        except Exception as e:
            print(f"Error initializing database connection: {e}")
            self.db = None

def select_db(username, password, hostname, port, database):
    """
    Function to select a database.

    Parameters:
        username (str): The username for the database connection.
        password (str): The password for the database connection.
        hostname (str): The hostname of the database server.
        port (int): The port number for the database connection.
        database (str): The name of the database.

    Returns:
        DatabaseConnection: A DatabaseConnection object representing the selected database.
    """
    return DatabaseConnection(username, password, hostname, port, database)
  
def get_db_config():
    """
    Function to retrieve database configuration from an API endpoint.

    Returns:
        dict or None: A dictionary containing database configuration if successful, otherwise None.
    """
    try:
        api_endpoint = 'http://192.168.14.28:84/db_connection'  
        response = requests.get(api_endpoint)
        if response.status_code == 200:
            return response.json().get('db_config')
        else:
            print(f"Error: Failed to retrieve db_config from API endpoint. Status code: {response.status_code}")
            return None
    except Exception as e:
        print(f"Error retrieving db_config: {e}")
        return None
  
def establish_db_connection():
    """
    Function to establish a database connection using configuration retrieved from an API endpoint.

    Returns:
        SQLDatabase or None: A SQLDatabase object representing the established database connection, or None if unsuccessful.
    """
    try:
        db_config = get_db_config()
        if db_config:
            return SQLDatabase.from_uri(
                f"postgresql://{db_config['username']}:{db_config['password']}@{db_config['hostname']}:{db_config['port']}/{db_config['database']}"
            )
        else:
            print("Error: Failed to obtain db_config from the API endpoint.")
            return None
    except requests.RequestException as e:
        print(f"Request to API endpoint failed: {e}")
        return None
    except KeyError as e:
        print(f"Missing key in db_config JSON: {e}")
        return None
    except Exception as e:
        print(f"Error establishing database connection: {e}")
        return None

**Comment by alexferl** [comment]
What does this have to do with this repo? You're not importing the extension and you're using PostgreSQL ...
