### ISSUE TITLE
Documentation down

### ISSUE THREAD

**Issue by benni336** [alexferl/flask-mysqldb#53]
Hello everyone,
I am trying to fiddle myself into it and I am searching for infos about the `Mysqldb.Waring` and `Mysqldb.Error`-Types for Error handling.
But the documentation which should be [here](https://flask-mysqldb.readthedocs.io/en/latest/) is not available anymore.

Could anyone have a look upon this, please? It is referenced at multiple places. For example in the pip docs.

**Comment by alexferl** [comment]
Hello,

Like mentioned in the README, this lib is just a thin wrapper around [mysqlclient](https://github.com/PyMySQL/mysqlclient) so you can look up their [exceptions](https://github.com/PyMySQL/mysqlclient/blob/main/src/MySQLdb/_exceptions.py).
