### ISSUE TITLE
flask-mysqldb support for Python3.6 ?

### ISSUE THREAD

**Issue by ghost** [alexferl/flask-mysqldb#6]
While `$sudo pip3 install flask-mysqldb`
Error Occurred : `MySQL config not found`

**Comment by alexferl** [comment]
Hello,

It's unrelated to Python 3.6, it's because you don't have MySQL installed or the binaries are not in your $PATH.

If you're on macOS:
`$ brew install mysql` and try to pip install again.
If that doesn't work try before running pip again:
`$ export PATH=$PATH:/usr/local/mysql/bin`

**Comment by ghost** [comment]
Oh so sorry that i have not mentioned which OS i using , I'm Ubuntu 14.04
This fixed the problem :+1: sudo apt-get install libmysqlclient-dev

**Comment by alexferl** [comment]
@sanjay555 No problem! Glad it works now.
